name: bdh-chexpert
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - pyspark==2.4.5
  - pytorch==1.4.0
  - torchvision==0.5.0
  - scikit-learn==0.22.1
  - opencv=4.1.1
  - numpy==1.18.1
  - scipy==1.4.1
  - pandas==1.0.2
  - matplotlib==3.1.3
  - jupyter==1.0.0
  - pytables==3.6.1
  - pyarrow==0.16.0
  - tqdm==4.45.0
  - tensorboardx==2.0
  - h5py==2.10.0
  - gpustat==0.6.0
  - pip:
    - petastorm
